### ISSUE TITLE
Pipeline failure due to: Failed to create the interpreter.

### ISSUE THREAD

**Issue by rayyan808** [pylon/spokestack-ios#124]
Hello,

I'm getting the error `Pipeline failure due to: Failed to create the interpreter.` when trying to run my application. The app configurations are correct as they work seamlessly on the Android codebase. Can I have an elaboration on this error?

```
AzureManager init
2021-08-20 13:09:03.865741+0200 Runner[10656:128311] Metal API Validation Enabled
2021-08-20 13:09:04.013476+0200 Runner[10656:128311] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600003b21000> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2021-08-20 13:09:04.500620+0200 Runner[10656:128311] Initialized TensorFlow Lite runtime.
Pipeline initialized.
2021-08-20 13:09:04.676435+0200 Runner[10656:128695] flutter: Observatory listening on http://127.0.0.1:53834/L4ASPbmCbtU=/
2021-08-20 13:09:04.690747+0200 Runner[10656:128311] Didn't find op for builtin opcode 'FULLY_CONNECTED' version '9'
2021-08-20 13:09:04.691000+0200 Runner[10656:128311] Registration failed.
Pipeline failure due to: Failed to create the interpreter.
2021-08-20 13:09:22.104875+0200 Runner[10656:128608] flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-08-20 13:09:22.105311+0200 Runner[10656:128608] flutter: │ #0   new FlutterSoundRecorder (package:flutter_sound/public/flutter_sound_recorder.dart:155:13)
2021-08-20 13:09:22.107288+0200 Runner[10656:128608] flutter: │ #1   new ExperimentController (package:elementa/app/modules/experiment/controllers/experiment_controller.dart:29:38)
2021-08-20 13:09:22.107543+0200 Runner[10656:128608] flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2021-08-20 13:09:22.108070+0200 Runner[10656:128608] flutter: │ 🐛 ctor: FlutterSoundRecorder()
2021-08-20 13:09:22.108586+0200 Runner[10656:128608] flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-08-20 13:09:22.668322+0200 Runner[10656:129100] [aurioc] AURemoteIO.h:323:entry: Unable to join I/O thread to workgroup ((null)): 2
iniSpokestack
Pipeline started.
```

It may be worth mentioning that in my Xcode debugger, I see the following error within my custom SpeechProcessor class:
```
extension NoteProcessor: SpeechProcessor {
    public var context: SpeechContext {
        get {
            return self.context >> ERROR: AURemoteIO::IOThread (45): EXC_BAD_ACCESS (code=2, address=0x70000aa6dff8)
            }
        set {
            self.context = newValue
            }
    }
```

Though I suspect this is simply due to the Pipeline never initialising, therefore the context is being sent to a deallocated Spokestack Delegate object? 

EDIT:
On further investigation, it seems the error:
`2021-08-20 13:09:04.690747+0200 Runner[10656:128311] Didn't find op for builtin opcode 'FULLY_CONNECTED' version '9'
2021-08-20 13:09:04.691000+0200 Runner[10656:128311] Registration failed.`
is thrown due to an issue with TensorFlow models or perhaps the runtime version of TFLite. It is not mentioned to explicitily import the `TensorFlowLiteSwift` module in the `Podfile`, I'm assuming Spokestack adds the module itself so it shouldn't be necessary? I will try adding this and see if this resolves the issue. I

**Comment by rayyan808** [comment]
Update: Added `TensorFlowLiteSwift` but this does not help. I'm a bit confused as to why this error is thrown and how it relates to TensorFlow, as the same exact models are utilized in the Android codebase of my application (which runs perfectly)

**Comment by rayyan808** [comment]
Looking at [similar built-in opcode ](https://github.com/tensorflow/tensorflow/issues/46409#issuecomment-830798848_)issues with TensorFlow, it seems the model may have been built with a version that is not the same as the one utilized by Spokestack. The models I am using (NLU + Wakeword/Keyword) have been made using Spokestack.

**Comment by noelweichbrodt** [comment]
Hi Ray, thanks for the issue updates. I've been trying to reproduce and still haven't had success on that front. You were initially correct, the cocoapods dependency on `TensorFlowLiteSwift` does not need to be explicitly specified since that is done by the `Spokestack-iOS` dependency. 

Based on the information you've posted so far, I do think your current hypothesis is correct, it sounds like the version of `TensorFlowLiteSwift` that you're running does not support an op in the model file. To help eliminate potential causes of that, I can confirm that a newly-trained Spokestack wake word model does work with the reference version `2.3.0` of `TensorFlowLiteSwift` (which is explicitly versioned in the `Spokestack-iOS` cocoapod). 

You can also verify the `TensorFlowLiteSwift` version that is actually being used in your project by examining the `Pods/Target Support Files/TensorFlowLiteSwift/TensorFlowLiteSwift-Info.plist` file for the `Bundle version string (short)` key. Also examine your `Podfile` and `Podfile.lock` contents in case there's a versioning override there.

**Comment by rayyan808** [comment]
Hello! Ive checked the `Bundle version short string` parameter, and it is indeed `2.3.0`. I've attached below my Podfile and Podfile.lock 

```
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Spokestack-iOS'
  pod 'MicrosoftCognitiveServicesSpeech-iOS'
  pod 'TensorFlowLiteSwift'
  pod 'SPPermissions/SpeechRecognizer'
  pod 'SPPermissions/Music'
  pod 'SPPermissions/Microphone'
  pod 'SPPermissions/Bluetooth'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
`Podfile.lock`:
```
PODS:
  - audiofileplayer (0.0.1):
    - Flutter
  - filter_audio (0.5.0)
  - Flutter (1.0.0)
  - flutter_sound (8.3.9):
    - Flutter
    - mobile-ffmpeg-audio (= 4.4.LTS)
    - tau_core (= 8.3.9)
  - flutter_tts (0.0.1):
    - Flutter
  - media_info (0.6.1):
    - Flutter
  - MicrosoftCognitiveServicesSpeech-iOS (1.18.0)
  - mobile-ffmpeg-audio (4.4.LTS)
  - path_provider (0.0.1):
    - Flutter
  - Spokestack-iOS (14.1.0):
    - filter_audio (~> 0.5.0)
    - TensorFlowLiteSwift (~> 2.3.0)
  - SPPermissions/Bluetooth (6.6.4):
    - SPPermissions/Core
  - SPPermissions/Core (6.6.4)
  - SPPermissions/Microphone (6.6.4):
    - SPPermissions/Core
  - SPPermissions/Music (6.6.4):
    - SPPermissions/Core
  - SPPermissions/SpeechRecognizer (6.6.4):
    - SPPermissions/Core
  - tau_core (8.3.9)
  - TensorFlowLiteC (2.3.0):
    - TensorFlowLiteC/Core (= 2.3.0)
  - TensorFlowLiteC/Core (2.3.0)
  - TensorFlowLiteSwift (2.3.0):
    - TensorFlowLiteSwift/Core (= 2.3.0)
  - TensorFlowLiteSwift/Core (2.3.0):
    - TensorFlowLiteC (= 2.3.0)

DEPENDENCIES:
  - audiofileplayer (from `.symlinks/plugins/audiofileplayer/ios`)
  - Flutter (from `Flutter`)
  - flutter_sound (from `.symlinks/plugins/flutter_sound/ios`)
  - flutter_tts (from `.symlinks/plugins/flutter_tts/ios`)
  - media_info (from `.symlinks/plugins/media_info/ios`)
  - MicrosoftCognitiveServicesSpeech-iOS
  - path_provider (from `.symlinks/plugins/path_provider/ios`)
  - Spokestack-iOS
  - SPPermissions/Bluetooth
  - SPPermissions/Microphone
  - SPPermissions/Music
  - SPPermissions/SpeechRecognizer
  - TensorFlowLiteSwift

SPEC REPOS:
  trunk:
    - filter_audio
    - MicrosoftCognitiveServicesSpeech-iOS
    - mobile-ffmpeg-audio
    - Spokestack-iOS
    - SPPermissions
    - tau_core
    - TensorFlowLiteC
    - TensorFlowLiteSwift

EXTERNAL SOURCES:
  audiofileplayer:
    :path: ".symlinks/plugins/audiofileplayer/ios"
  Flutter:
    :path: Flutter
  flutter_sound:
    :path: ".symlinks/plugins/flutter_sound/ios"
  flutter_tts:
    :path: ".symlinks/plugins/flutter_tts/ios"
  media_info:
    :path: ".symlinks/plugins/media_info/ios"
  path_provider:
    :path: ".symlinks/plugins/path_provider/ios"

SPEC CHECKSUMS:
  audiofileplayer: 4aaff759a721ec3a850a682e0d9ec554e5f9e86f
  filter_audio: 1f071989c5a9ad0e0c9c45d08084513deb30d065
  Flutter: 434fef37c0980e73bb6479ef766c45957d4b510c
  flutter_sound: 91c069f33d811a4c98b9aa7cec9cd1dbfd1786d9
  flutter_tts: 0f492aab6accf87059b72354fcb4ba934304771d
  media_info: 32d75eec667b09571616de41b194abb96670bc22
  MicrosoftCognitiveServicesSpeech-iOS: bbadeabef1f5182d75942c15e1b7885095a61dc7
  mobile-ffmpeg-audio: 1e0a053f8a6de57114e50ff48b3a85ff1c60f902
  path_provider: abfe2b5c733d04e238b0d8691db0cfd63a27a93c
  Spokestack-iOS: 090ed0e757276f2407beec82fa851ec3e408b5b9
  SPPermissions: 0e696595ccf68d9a84af8109a350d9153264f7d9
  tau_core: f7bbd1c6a632f52c2fa7c14feea385ab966b1e45
  TensorFlowLiteC: 51f50caf5777f740a70e2c1a5dbdc149e7aeb50b
  TensorFlowLiteSwift: fb152cc1eec36b25b03a23c07f5d58113170af58

PODFILE CHECKSUM: fac5dcf567c0843c4f933eda94c024ef9815d8ff

COCOAPODS: 1.11.0.beta.2
```
Note: I explicitly added the TensorFlowLiteSwift pod as mentioned above, removing it does not alter the outcome.

Is there anything else I can share that will help?

**Comment by rayyan808** [comment]
@noelweichbrodt I can confirm that this issue is somehow related to the models, as I could not reproduce the error using the provided spokestack pre-built models. I've attached the models below, my colleague obtained these models through Spokestack itself, and one of your colleagues (@space-pope ) kindly helped make the NLU after we ran into some build issues. So it is not custom made by ourselves, the wake word models are also from the wakeword 'spokestack'
Temporary link to the models: https://easyupload.io/ny0sow

**Comment by noelweichbrodt** [comment]
Thank you for providing that Ray, I can reproduce your error with the NLU model. The wake word models are nominal. While I investigate a fix, just not initializing the NLU model (or alternatively using a different NLU model provided in Maker like `high-low`) in iOS will function as a workaround.

To help with my investigation, what version of TensorFlowLite are you using on Android?

**Comment by rayyan808** [comment]
> Thank you for providing that Ray, I can reproduce your error with the NLU model. The wake word models are nominal. While I investigate a fix, just not initializing the NLU model (or alternatively using a different NLU model provided in Maker like `high-low`) in iOS will function as a workaround.
> 
> To help with my investigation, what version of TensorFlowLite are you using on Android?


I am using `2.4.0`, perhaps the models are not backwards compatible? I cannot explicitly change the version from the `Podfile` as it says 
```
[!] CocoaPods could not find compatible versions for pod "TensorFlowLiteSwift":
  In Podfile:
    Spokestack-iOS was resolved to 14.1.0, which depends on
      TensorFlowLiteSwift (~> 2.3.0)

    TensorFlowLiteSwift (~> 2.4.0)
 ```

**Comment by noelweichbrodt** [comment]
I'm testing 2.4.0 right now and it has no issues for wake word and nlu. To manually update as you're attempting, edit the `TensorFlowLiteSwift` version in `Spokestack-iOS.podspec` and perform another `pod install`. I'll also be releasing a new version of `Spokestack-iOS` that will update the `TensorFlowLiteSwift` dep to 2.6.0 pending successful testing.

**Comment by noelweichbrodt** [comment]
`Spokestack-iOS` version `14.2.0` is now available on Cocoapods. This version updates the `TensorFlowLiteSwift` dep to `2.6.0`, which in my testing fixed the `Didn't find op for builtin opcode 'FULLY_CONNECTED' version '9'` error when loading your nlu model. Thanks for working with me to figure this out!

**Comment by rayyan808** [comment]
> `Spokestack-iOS` version `14.2.0` is now available on Cocoapods. This version updates the `TensorFlowLiteSwift` dep to `2.6.0`, which in my testing fixed the `Didn't find op for builtin opcode 'FULLY_CONNECTED' version '9'` error when loading your nlu model. Thanks for working with me to figure this out!

No problem! Glad we solved this :)
