### ISSUE TITLE
Return/Callback values for start/stop

### ISSUE THREAD

**Issue by rayyan808** [pylon/spokestack-ios#127]
Hello,
In my application, there is constant turning on and off of the `SpeechPipeline`, this is because I have integrated `Azure TTS` which must not play during an active pipeline as it causes non-deterministic results (ASR begins interpreting TTS, sometimes TTS activates before pipeline has released resources). I am aware of the `didStop` and `didStart` within `SpokestackDelegate`, but this is more of a hassle to use as I have many other instances in which `start` or `stop` may be invoked whilst navigating through the application. This means keeping track of each caller of the pipeline toggles as well as a global state, currently I am doing something similar with `NotificationCenter` but I feel an easier & cleaner approach would be to have a callback from the pipeline toggling. 
It would be very useful for my use-case to be able to call something such as:
```
let resourceFlushed  = await pipeline.close();
switch(resourceFlushed) {
      case let .success():
      //invokeTTS here
      let resourceObtained = await pipeline.start();
            switch(resourceObtained) {
                case let .success():
                case let .failure(error):

        }
       case let .failure(error): 
        }
```

**Comment by noelweichbrodt** [comment]
I like this idea. Unfortunately, we deliberately do not utilize a callback style due to ObjC compatibility requirements, but I'd be happy to review a PR request callback additions as a nightly-style release!
